import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Footer from '../components/Footer'
import { Fragment } from 'react/cjs/react.production.min'




export default function Home() {
  return (
      



    
      
    <Fragment>

        
        <Head>
            <title>Play you game folks !</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
        <div className="container">
            <Header />
        </div>

        <section id="scroll">
            <div className={styles.jumbotron1}>
                <h1 className="display-4">PLAY TRADITIONAL GAME</h1>
                <p className="lead">Experience new traditional game play</p>
                <a className="btn btn-warning btn-lg" href="/login" role="button">PLAY NOW</a>
            </div>
        </section>

        <section id="scroll">
            <div className="styles.container px-5">
                <div className="row gx-5 align-items-center">
                    <div className="col-lg-6 order-lg-2">
                        {/* <div className="p-5"><Image className="img-fluid rounded-circle" src="assets/image/01.jpg" alt="..." /></div> */}
                    </div>
                    <div className="col-lg-6 order-lg-1">
                        <div className="p-5">
                            <h2 className={styles.display_5}>Rock Paper Scissors</h2>
                            <p className={styles.display_10}>Rock paper scissors (also known by other orderings of the three items, with rock sometimes being called stone, or as Rochambeau, roshambo, or ro-sham-bo)  is a hand game, usually played between two people, in which each player simultaneously forms one of three shapes with an outstretched hand. These shapes are rock (a closed fist), paper (a flat hand), and scissors (a fist with the index finger and middle finger extended, forming a V). Scissors is identical to the two-fingered V sign (also indicating victory or peace) except that it is pointed horizontally instead of being held upright in the air.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section className={styles.sistem_req}>
            <div className="sub-judul-sysreq">
                <h5 className={styles.special_3}>Can My Computer Run This Game?</h5>
            </div>

            <div className={styles.row}>
                <div className="col-lg-5">
                    <h1 className={styles.sysreq_title}>SYSTEM REQUIREMENTS</h1>
                    <table className="table table-bordered table-content-sys m-5">
                        <tbody>
                        <tr>
                        <td>
                            <h2 className="text-warning">OS:</h2>
                            <p className={styles.requirements_info_content}>
                            Windows 7 64-bit only<br/>(No OSX support at this time)
                            </p>
                        </td>
                        <td>
                            <h2 className="requirements-info text-warning">Processor:</h2>
                            <p className={styles.requirements_info_content}>Intel Core 2 Duo @2.4GHz or AMD Athlon X2 @ 2.8GHz</p>
                        </td>
                        </tr>
                        <tr>
                        <td>
                            <h2 className="requirements-info text-warning">Memory:</h2>
                            <p className={styles.requirements_info_content}>4 GB RAM</p>
                        </td>
                        <td>
                            <h2 className="requirements-info text-warning">Storage:</h2>
                            <p className={styles.requirements_info_content}>8 GB available space</p>
                        </td>
                        </tr>
                        <tr>
                        <td colSpan="2">
                            <h2 className="requirements-info text-warning">Graphics:</h2>
                            <p className={styles.requirements_info_content}>
                            NVIDIA GeForce GTX 660 2GB or<br/>AMD Radeon HD 7850 2GB
                            DirectX11 (Shader Model S)
                            </p>
                        </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>

        <Footer />
            
            

        </main>
        
        

        




    </Fragment>
    
  )
}
